購入画面と明細画面を出力するための処理を実装しました。
Kiho-F101/lamp_practice pull request #12
Opened 2021-05-08 15:22 UTC by Kiho-F101

@primestyleus 
タイトルの通り、実装しました。
model/cart.phpでエラーが出ています。{}の数が会ってないのかもしれないの思いどこが間違っているか何回も確認したのですが、エラーの場所が特定できませんでした。こういった場合、先生や上司の方に見ていただけるのでしょうか・・・？自分で解決できず申し訳ありません。

2021-05-08 16:21 UTC, primestyleus commented
@Kiho-F101 
> こういった場合、先生や上司の方に見ていただけるのでしょうか・・・？自分で解決できず申し訳ありません。

もちろんです！一人でちょっと悩んでも解決しない場合は、積極的に質問しましょう。
とりわけ会社では、あるところでずっと止まってしまって進捗が遅れることのほうが問題となります。よく言われることですが、「15分悩んでも進まなかったら質問する」とよいとおもいます。コードはこれから確認しますね！

2021-05-08 17:18 UTC, primestyleus requested changes
@Kiho-F101 
実装方法についてはこちらで問題ないです。よくできていますね！
エラーについては、閉じ括弧が抜けている箇所がありました。補完にも細かい部分で修正箇所があるので、それぞれの修正箇所のコメントを見ていただければと思います。

2021-05-08 17:18 UTC, primestyleus commented on www/model/cart.php
> +  if(count($_SESSION['__errors']===0){
`['__errors']` のあとに `)` が抜けているようです！

2021-05-08 17:18 UTC, primestyleus commented on www/model/cart.php
> +    Price
DB定義にあわせて amount, price と小文字にしましょう。

2021-05-08 17:18 UTC, primestyleus commented on www/model/cart.php
> +Function regist_purchase_histories($db, $user_id, $datetime){
`function` と小文字はじまりにしましょう。

2021-05-08 17:18 UTC, primestyleus commented on www/model/cart.php
> +  Function regist_purchase_details($db, $order_number, $item_id, $amount, $price){
`function` と小文字はじまりにしましょう。

2021-05-09 06:48 UTC, Kiho-F101 commented on www/model/cart.php
> +  Function regist_purchase_details($db, $order_number, $item_id, $amount, $price){
@primestyleus 
ありがとうございました！泣
{}ばかり見ていたらset_errorの閉じかっこだったのですね・・・すみませんでした。
いくつかご指摘いただいたところも含めて、修正しました。よろしくお願いいたします。

2021-05-09 07:06 UTC, primestyleus approved these changes
@Kiho-F101 
修正確認しました! お疲れさまでした。マージしますね。

2021-05-09 07:06 UTC, merged