CSRF対策を実装しました。
Kiho-F101/lamp_practice pull request #8
Opened 2021-04-29 11:56 UTC by Kiho-F101

@primestyleus 
対象のファイルでCSRF対策を実装しました。マージお願いします。

2021-04-29 14:26 UTC, primestyleus requested changes
@Kiho-F101 
トークンの設定についてはokです。照合部分が今のままだと正しく動かないと思います。実際に画面から動作確認もしてみてください。

2021-04-29 14:26 UTC, primestyleus commented on www/html/admin_change_status.php
> +if(is_valid_csrf_token($token)===FALSE){
説明が漏れていたかもしれませんが、$token という変数はpost されたものを事前に取得しておくことが必要です。

2021-04-30 15:04 UTC, Kiho-F101 commented on www/html/admin_change_status.php
> +if(is_valid_csrf_token($token)===FALSE){
@primestyleus 
修正しました。この画面のままマージできますか？それとも、また新しいプルリクエストを作成すべきですか？

2021-04-30 15:06 UTC, primestyleus commented on www/html/admin_change_status.php
> +if(is_valid_csrf_token($token)===FALSE){
@Kiho-F101 
このままでokです。確認します！

2021-04-30 15:11 UTC, primestyleus approved these changes
@Kiho-F101 
修正ありがとうございました。こちらで問題なさそうですのでマージします！

2021-04-30 15:11 UTC, merged

2021-04-30 15:13 UTC, Kiho-F101 commented
@primestyleus 
ありがとうございました！